import { activeVersion } from './versions'
import { soundingTuning } from './instrument'
import {
  connectedTechnique,
  validateConnectedTechniqueFingerings,
  type ConnectedTechnique,
} from './fingering'
import type {
  EditorProject,
  ExportArtifact,
  ExportFormat,
  NoteEvent,
} from './types'

const PITCH_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
const PROJECT_FORMAT = 'solotrace-project'
const PROJECT_SCHEMA_VERSION = 1

function pitchName(midiPitch: number): string {
  return `${PITCH_NAMES[((midiPitch % 12) + 12) % 12]}${Math.floor(midiPitch / 12) - 1}`
}

function textBytes(value: string): Uint8Array {
  return new TextEncoder().encode(value)
}

interface TechniqueConnection {
  technique: ConnectedTechnique
  marker: 'h' | 'p' | '/' | '\\'
}

function techniqueConnection(
  previous: NoteEvent,
  current: NoteEvent,
): TechniqueConnection | undefined {
  const technique = connectedTechnique(current)
  if (!technique) return undefined
  if (technique === 'hammer-on') return { technique, marker: 'h' }
  if (technique === 'pull-off') return { technique, marker: 'p' }
  return { technique, marker: current.fret > previous.fret ? '/' : '\\' }
}

function techniqueSuffix(note: NoteEvent): string {
  let suffix = ''
  if (note.techniques.includes('bend')) suffix += 'b'
  if (note.techniques.includes('vibrato')) suffix += '~'
  return suffix
}

export function asciiTab(project: EditorProject, width = 72): string {
  const tab = activeVersion(project).tab
  if (tab.notes.length === 0) return 'No notes yet.\n'
  if (!Number.isInteger(width) || width < 8) throw new Error('ASCII tab width must be at least 8')
  const start = project.passage.start_s
  const duration = Math.max(0.01, project.passage.end_s - start)
  const lines = new Map<number, string[]>()
  for (let string = 1; string <= tab.tuning.length; string += 1) {
    lines.set(string, Array<string>(width).fill('-'))
  }
  const notes = [...tab.notes].sort(
    (left, right) => left.audio_onset_s - right.audio_onset_s || left.string - right.string,
  )
  validateConnectedTechniqueFingerings(notes)
  notes.forEach((note, index) => {
    const line = lines.get(note.string)
    if (!line) throw new Error(`String ${note.string} is outside this guitar range`)
    let column = Math.min(
      width - 2,
      Math.max(0, Math.round(((note.audio_onset_s - start) / duration) * (width - 3))),
    )
    const previous = notes[index - 1]
    const connection = previous && techniqueConnection(previous, note)
    const token = `${connection?.marker ?? ''}${note.fret}${techniqueSuffix(note)}`
    while (true) {
      const required = column + token.length + 1
      if (required > line.length) {
        const extension = required - line.length
        for (const value of lines.values()) value.push(...Array<string>(extension).fill('-'))
      }
      if (token.split('').every((_, offset) => line[column + offset] === '-')) break
      column += 1
    }
    token.split('').forEach((character, offset) => {
      line[column + offset] = character
    })
  })

  const labels = soundingTuning(tab)
    .reverse()
    .map((openPitch, index) => ({ string: index + 1, label: pitchName(openPitch) }))
  const result = [`${project.title} — ${project.passage.name}`, '']
  for (const { string, label } of labels) {
    result.push(`${label.padStart(3, ' ')}|${lines.get(string)!.join('')}|`)
  }
  result.push('', 'Generated by SoloTrace; verify uncertain notes against the recording.')
  return `${result.join('\n')}\n`
}

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function pitchParts(midiPitch: number): [string, number, number] {
  const names: [string, number][] = [
    ['C', 0], ['C', 1], ['D', 0], ['D', 1], ['E', 0], ['F', 0],
    ['F', 1], ['G', 0], ['G', 1], ['A', 0], ['A', 1], ['B', 0],
  ]
  const [step, alter] = names[((midiPitch % 12) + 12) % 12]
  return [step, alter, Math.floor(midiPitch / 12) - 1]
}

interface MeasureNote {
  event: NoteEvent
  measureNumber: number
  startTick: number
  durationTicks: number
  tieStop: boolean
  tieStart: boolean
}

function measureTicks(project: EditorProject): number {
  const tab = activeVersion(project).tab
  const [beats, beatType] = tab.time_signature
  if (beats <= 0 || beatType <= 0) throw new Error('Time signature values must be positive')
  const ticks = (beats * tab.ticks_per_quarter * 4) / beatType
  if (!Number.isInteger(ticks)) {
    throw new Error('Time signature cannot be represented exactly with current ticks-per-quarter value')
  }
  return ticks
}

function splitMusicXmlNotes(project: EditorProject, ticksPerMeasure: number): MeasureNote[] {
  const segments: MeasureNote[] = []
  let previousEnd = 0
  const notes = [...activeVersion(project).tab.notes].sort(
    (left, right) => left.score_tick - right.score_tick || left.id.localeCompare(right.id),
  )
  for (const event of notes) {
    if (event.score_tick < previousEnd) {
      throw new Error('MusicXML export requires a monophonic tab without overlapping notes')
    }
    const eventEnd = event.score_tick + event.duration_ticks
    let segmentStart = event.score_tick
    while (segmentStart < eventEnd) {
      const measureIndex = Math.floor(segmentStart / ticksPerMeasure)
      const segmentEnd = Math.min(eventEnd, (measureIndex + 1) * ticksPerMeasure)
      segments.push({
        event,
        measureNumber: measureIndex + 1,
        startTick: segmentStart,
        durationTicks: segmentEnd - segmentStart,
        tieStop: segmentStart > event.score_tick,
        tieStart: segmentEnd < eventEnd,
      })
      segmentStart = segmentEnd
    }
    previousEnd = eventEnd
  }
  return segments
}

function musicXmlNote(
  segment: MeasureNote,
  incoming?: TechniqueConnection,
  outgoing?: TechniqueConnection,
): string[] {
  const { event } = segment
  const [step, alter, octave] = pitchParts(event.midi_pitch)
  const lines = ['    <note>', '      <pitch>', `        <step>${step}</step>`]
  if (alter) lines.push(`        <alter>${alter}</alter>`)
  lines.push(
    `        <octave>${octave}</octave>`,
    '      </pitch>',
    `      <duration>${segment.durationTicks}</duration>`,
  )
  if (segment.tieStop) lines.push('      <tie type="stop"/>')
  if (segment.tieStart) lines.push('      <tie type="start"/>')
  lines.push('      <voice>1</voice>', '      <notations>')
  if (segment.tieStop) lines.push('        <tied type="stop"/>')
  if (segment.tieStart) lines.push('        <tied type="start"/>')
  if (!segment.tieStop && incoming?.technique === 'slide') {
    lines.push('        <slide type="stop" number="1"/>')
  }
  if (!segment.tieStart && outgoing?.technique === 'slide') {
    lines.push('        <slide type="start" number="1"/>')
  }
  lines.push(
    '        <technical>',
    `          <string>${event.string}</string>`,
    `          <fret>${event.fret}</fret>`,
  )
  if (
    !segment.tieStop &&
    (incoming?.technique === 'hammer-on' || incoming?.technique === 'pull-off')
  ) {
    const element = incoming.technique
    const label = incoming.technique === 'hammer-on' ? 'H' : 'P'
    lines.push(`          <${element} type="stop">${label}</${element}>`)
  }
  if (
    !segment.tieStart &&
    (outgoing?.technique === 'hammer-on' || outgoing?.technique === 'pull-off')
  ) {
    const element = outgoing.technique
    const label = outgoing.technique === 'hammer-on' ? 'H' : 'P'
    lines.push(`          <${element} type="start">${label}</${element}>`)
  }
  if (!segment.tieStop && incoming?.technique === 'slide') {
    lines.push(`          <other-technical>${incoming.marker}</other-technical>`)
  }
  if (event.techniques.includes('bend')) {
    const curve = event.pitch_curve_cents
    let bendCents = curve.length ? Math.max(...curve) - Math.min(...curve) : 100
    if (bendCents <= 0) bendCents = 100
    lines.push(
      '          <bend>',
      `            <bend-alter>${Math.round((bendCents / 100) * 100) / 100}</bend-alter>`,
      '          </bend>',
    )
  }
  if (event.techniques.includes('vibrato')) {
    lines.push('          <other-technical>vibrato</other-technical>')
  }
  lines.push('        </technical>', '      </notations>', '    </note>')
  return lines
}

export function musicXml(project: EditorProject): string {
  const tab = activeVersion(project).tab
  const ticksPerMeasure = measureTicks(project)
  const orderedNotes = [...tab.notes].sort(
    (left, right) => left.score_tick - right.score_tick || left.id.localeCompare(right.id),
  )
  validateConnectedTechniqueFingerings(orderedNotes)
  const incomingConnections = new Map<string, TechniqueConnection>()
  const outgoingConnections = new Map<string, TechniqueConnection>()
  orderedNotes.slice(1).forEach((note, index) => {
    const previous = orderedNotes[index]
    const connection = techniqueConnection(previous, note)
    if (!connection) return
    incomingConnections.set(note.id, connection)
    outgoingConnections.set(previous.id, connection)
  })
  const segments = splitMusicXmlNotes(project, ticksPerMeasure)
  const grouped = new Map<number, MeasureNote[]>()
  for (const segment of segments) {
    grouped.set(segment.measureNumber, [...(grouped.get(segment.measureNumber) ?? []), segment])
  }
  const lastMeasure = Math.max(1, ...grouped.keys())
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<score-partwise version="4.0">',
    '  <work>',
    `    <work-title>${xmlEscape(project.title)}</work-title>`,
    '  </work>',
    '  <part-list>',
    '    <score-part id="P1"><part-name>Lead guitar</part-name></score-part>',
    '  </part-list>',
    '  <part id="P1">',
  ]
  for (let measureNumber = 1; measureNumber <= lastMeasure; measureNumber += 1) {
    lines.push(`  <measure number="${measureNumber}">`)
    if (measureNumber === 1) {
      const [beats, beatType] = tab.time_signature
      lines.push(
        '    <attributes>',
        `      <divisions>${tab.ticks_per_quarter}</divisions>`,
        `      <time><beats>${beats}</beats><beat-type>${beatType}</beat-type></time>`,
        '      <clef><sign>TAB</sign><line>5</line></clef>',
        '      <staff-details>',
        `        <staff-lines>${tab.tuning.length}</staff-lines>`,
      )
      if (tab.capo_fret) lines.push(`        <capo>${tab.capo_fret}</capo>`)
      tab.tuning.forEach((openPitch, index) => {
        const [step, alter, octave] = pitchParts(openPitch)
        lines.push(
          `        <staff-tuning line="${index + 1}">`,
          `          <tuning-step>${step}</tuning-step>`,
        )
        if (alter) lines.push(`          <tuning-alter>${alter}</tuning-alter>`)
        lines.push(`          <tuning-octave>${octave}</tuning-octave>`, '        </staff-tuning>')
      })
      lines.push(
        '      </staff-details>',
        '    </attributes>',
        '    <direction placement="above">',
        '      <direction-type><metronome><beat-unit>quarter</beat-unit>',
        `        <per-minute>${tab.tempo_bpm}</per-minute></metronome></direction-type>`,
        `      <sound tempo="${tab.tempo_bpm}"/>`,
        '    </direction>',
      )
    }
    let cursor = (measureNumber - 1) * ticksPerMeasure
    const measureSegments = grouped.get(measureNumber) ?? []
    measureSegments.forEach((segment) => {
      if (segment.startTick > cursor) {
        lines.push(`    <forward><duration>${segment.startTick - cursor}</duration></forward>`)
      }
      lines.push(
        ...musicXmlNote(
          segment,
          incomingConnections.get(segment.event.id),
          outgoingConnections.get(segment.event.id),
        ),
      )
      cursor = segment.startTick + segment.durationTicks
    })
    lines.push('  </measure>')
  }
  lines.push('  </part>', '</score-partwise>')
  return `${lines.join('\n')}\n`
}

function variableLength(value: number): number[] {
  if (!Number.isSafeInteger(value) || value < 0) throw new Error('MIDI delta must be non-negative')
  const bytes = [value % 128]
  let remaining = Math.floor(value / 128)
  while (remaining > 0) {
    bytes.unshift((remaining % 128) | 0x80)
    remaining = Math.floor(remaining / 128)
  }
  return bytes
}

function bigEndian16(value: number): number[] {
  return [(value >>> 8) & 0xff, value & 0xff]
}

function bigEndian32(value: number): number[] {
  return [(value >>> 24) & 0xff, (value >>> 16) & 0xff, (value >>> 8) & 0xff, value & 0xff]
}

function latin1(value: string): number[] {
  return [...value].map((character) => {
    const code = character.codePointAt(0)!
    return code <= 0xff ? code : 0x3f
  })
}

function timeSignatureMeta(timeSignature: readonly [number, number]): number[] {
  const [numerator, denominator] = timeSignature
  const denominatorPower = Math.log2(denominator)
  if (
    !Number.isInteger(numerator) ||
    numerator <= 0 ||
    numerator > 0xff ||
    !Number.isInteger(denominatorPower) ||
    denominatorPower < 0 ||
    denominatorPower > 7
  ) {
    throw new Error('MIDI time signature requires a positive numerator and power-of-two denominator')
  }
  const clocksPerClick = denominator === 8 && numerator > 3 && numerator % 3 === 0 ? 36 : 24
  return [0x00, 0xff, 0x58, 0x04, numerator, denominatorPower, clocksPerClick, 0x08]
}

export function midi(project: EditorProject): Uint8Array {
  const tab = activeVersion(project).tab
  if (tab.ticks_per_quarter <= 0 || tab.ticks_per_quarter > 0x7fff) {
    throw new Error('MIDI ticks-per-quarter must be between 1 and 32767')
  }
  const title = latin1(project.title)
  const tempo = Math.max(1, Math.min(0xffffff, Math.round(60_000_000 / tab.tempo_bpm)))
  const track = [
    0x00, 0xff, 0x03, ...variableLength(title.length), ...title,
    0x00, 0xff, 0x51, 0x03, (tempo >>> 16) & 0xff, (tempo >>> 8) & 0xff, tempo & 0xff,
    ...timeSignatureMeta(tab.time_signature),
  ]
  const events: { tick: number; order: number; bytes: number[] }[] = []
  const notes = [...tab.notes].sort(
    (left, right) => left.score_tick - right.score_tick || left.id.localeCompare(right.id),
  )
  validateConnectedTechniqueFingerings(notes)
  for (const note of notes) {
    if (!Number.isInteger(note.midi_pitch) || note.midi_pitch < 0 || note.midi_pitch > 127) {
      throw new Error(`MIDI pitch ${note.midi_pitch} is outside 0..127`)
    }
    events.push({ tick: note.score_tick, order: 1, bytes: [0x90, note.midi_pitch, 82] })
    events.push({
      tick: note.score_tick + note.duration_ticks,
      order: 0,
      bytes: [0x80, note.midi_pitch, 0],
    })
  }
  events.sort((left, right) => left.tick - right.tick || left.order - right.order)
  let previousTick = 0
  for (const event of events) {
    track.push(...variableLength(event.tick - previousTick), ...event.bytes)
    previousTick = event.tick
  }
  track.push(0x00, 0xff, 0x2f, 0x00)
  return new Uint8Array([
    0x4d, 0x54, 0x68, 0x64,
    ...bigEndian32(6),
    ...bigEndian16(1),
    ...bigEndian16(1),
    ...bigEndian16(tab.ticks_per_quarter),
    0x4d, 0x54, 0x72, 0x6b,
    ...bigEndian32(track.length),
    ...track,
  ])
}

export interface ProjectJsonOptions {
  allVersions?: boolean
  appVersion?: string
}

export function projectJson(
  project: EditorProject,
  options: ProjectJsonOptions = {},
): string {
  const payload = options.allVersions
    ? project
    : {
        ...project,
        versions: project.versions.filter((version) => version.id === project.active_version_id),
      }
  return `${JSON.stringify(
    {
      format: PROJECT_FORMAT,
      schemaVersion: PROJECT_SCHEMA_VERSION,
      appVersion: options.appVersion ?? 'hosted',
      project: payload,
    },
    null,
    2,
  )}\n`
}

export function exportFilename(project: EditorProject, format: ExportFormat): string {
  const asciiTitle = project.title
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\x00-\x7F]/g, '')
  const safeTitle = asciiTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || project.id
  const suffix: Record<ExportFormat, string> = {
    json: '.solotrace.json',
    musicxml: '.musicxml',
    midi: '.mid',
    ascii: '.txt',
  }
  return `${safeTitle}${suffix[format]}`
}

export interface ExportProjectOptions extends ProjectJsonOptions {
  asciiWidth?: number
}

export function exportProject(
  project: EditorProject,
  format: ExportFormat,
  options: ExportProjectOptions = {},
): ExportArtifact {
  const mimeTypes: Record<ExportFormat, string> = {
    json: 'application/json',
    musicxml: 'application/vnd.recordare.musicxml+xml',
    midi: 'audio/midi',
    ascii: 'text/plain; charset=utf-8',
  }
  let bytes: Uint8Array
  if (format === 'json') bytes = textBytes(projectJson(project, options))
  else if (format === 'musicxml') bytes = textBytes(musicXml(project))
  else if (format === 'midi') bytes = midi(project)
  else bytes = textBytes(asciiTab(project, options.asciiWidth))
  return {
    format,
    filename: exportFilename(project, format),
    mimeType: mimeTypes[format],
    bytes,
  }
}
