from __future__ import annotations

import io
import json
import unicodedata
import zipfile
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from xml.etree import ElementTree as ET

import mido

from .models import NoteEvent, Project

PITCH_NAMES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")


def pitch_name(midi_pitch: int) -> str:
    return f"{PITCH_NAMES[midi_pitch % 12]}{midi_pitch // 12 - 1}"


def ascii_tab(project: Project, width: int = 72) -> str:
    notes = project.tab.notes
    if not notes:
        return "No notes yet.\n"
    start = project.passage.start_s
    end = project.passage.end_s
    duration = max(0.01, end - start)
    string_count = len(project.tab.tuning)
    lines = {string: ["-"] * width for string in range(1, string_count + 1)}
    for note in sorted(notes, key=lambda item: (item.audio_onset_s, item.string)):
        column = min(
            width - 2,
            max(0, round((note.audio_onset_s - start) / duration * (width - 3))),
        )
        text = str(note.fret)
        if "bend" in note.techniques:
            text += "b"
        while True:
            required = column + len(text) + 1
            if required > len(lines[note.string]):
                extension = required - len(lines[note.string])
                for line in lines.values():
                    line.extend("-" * extension)
            if all(
                lines[note.string][column + offset] == "-"
                for offset in range(len(text))
            ):
                break
            column += 1
        for offset, character in enumerate(text):
            lines[note.string][column + offset] = character
    labels = {
        string: pitch_name(open_pitch)
        for string, open_pitch in enumerate(reversed(project.tab.tuning), start=1)
    }
    result = [f"{project.title} — {project.passage.name}", ""]
    result.extend(
        f"{labels[string]:>3}|{''.join(lines[string])}|"
        for string in range(1, string_count + 1)
    )
    result.append("")
    result.append("Generated by SoloTrace; verify uncertain notes against the recording.")
    return "\n".join(result) + "\n"


def _pitch_parts(midi_pitch: int) -> tuple[str, int, int]:
    names = [
        ("C", 0),
        ("C", 1),
        ("D", 0),
        ("D", 1),
        ("E", 0),
        ("F", 0),
        ("F", 1),
        ("G", 0),
        ("G", 1),
        ("A", 0),
        ("A", 1),
        ("B", 0),
    ]
    step, alter = names[midi_pitch % 12]
    octave = midi_pitch // 12 - 1
    return step, alter, octave


@dataclass(frozen=True)
class _MeasureNote:
    event: NoteEvent
    measure_number: int
    start_tick: int
    duration_ticks: int
    tie_stop: bool
    tie_start: bool


def _measure_ticks(project: Project) -> int:
    beats, beat_type = project.tab.time_signature
    if beats <= 0 or beat_type <= 0:
        raise ValueError("Time signature values must be positive")
    measure_ticks = Fraction(
        beats * project.tab.ticks_per_quarter * 4,
        beat_type,
    )
    if measure_ticks.denominator != 1:
        raise ValueError(
            "Time signature cannot be represented exactly with the current "
            "ticks-per-quarter value"
        )
    return measure_ticks.numerator


def _split_musicxml_notes(project: Project, ticks_per_measure: int) -> list[_MeasureNote]:
    segments: list[_MeasureNote] = []
    previous_end = 0
    for event in sorted(project.tab.notes, key=lambda note: (note.score_tick, note.id)):
        if event.score_tick < previous_end:
            raise ValueError("MusicXML export requires a monophonic tab without overlapping notes")
        event_end = event.score_tick + event.duration_ticks
        segment_start = event.score_tick
        while segment_start < event_end:
            measure_index = segment_start // ticks_per_measure
            measure_end = (measure_index + 1) * ticks_per_measure
            segment_end = min(event_end, measure_end)
            segments.append(
                _MeasureNote(
                    event=event,
                    measure_number=measure_index + 1,
                    start_tick=segment_start,
                    duration_ticks=segment_end - segment_start,
                    tie_stop=segment_start > event.score_tick,
                    tie_start=segment_end < event_end,
                )
            )
            segment_start = segment_end
        previous_end = event_end
    return segments


def _append_musicxml_note(measure: ET.Element, segment: _MeasureNote) -> None:
    event = segment.event
    note = ET.SubElement(measure, "note")
    pitch = ET.SubElement(note, "pitch")
    step, alter, octave = _pitch_parts(event.midi_pitch)
    ET.SubElement(pitch, "step").text = step
    if alter:
        ET.SubElement(pitch, "alter").text = str(alter)
    ET.SubElement(pitch, "octave").text = str(octave)
    ET.SubElement(note, "duration").text = str(segment.duration_ticks)
    if segment.tie_stop:
        ET.SubElement(note, "tie", type="stop")
    if segment.tie_start:
        ET.SubElement(note, "tie", type="start")
    ET.SubElement(note, "voice").text = "1"
    notations = ET.SubElement(note, "notations")
    if segment.tie_stop:
        ET.SubElement(notations, "tied", type="stop")
    if segment.tie_start:
        ET.SubElement(notations, "tied", type="start")
    technical = ET.SubElement(notations, "technical")
    ET.SubElement(technical, "string").text = str(event.string)
    ET.SubElement(technical, "fret").text = str(event.fret)
    if "bend" in event.techniques:
        bend = ET.SubElement(technical, "bend")
        bend_cents = (
            max(event.pitch_curve_cents) - min(event.pitch_curve_cents)
            if event.pitch_curve_cents
            else 100
        )
        if bend_cents <= 0:
            bend_cents = 100
        ET.SubElement(bend, "bend-alter").text = str(
            round(bend_cents / 100, 2)
        )


def musicxml(project: Project) -> bytes:
    score = ET.Element("score-partwise", version="4.0")
    work = ET.SubElement(score, "work")
    ET.SubElement(work, "work-title").text = project.title
    part_list = ET.SubElement(score, "part-list")
    score_part = ET.SubElement(part_list, "score-part", id="P1")
    ET.SubElement(score_part, "part-name").text = "Lead guitar"
    part = ET.SubElement(score, "part", id="P1")
    divisions = project.tab.ticks_per_quarter
    ticks_per_measure = _measure_ticks(project)
    segments = _split_musicxml_notes(project, ticks_per_measure)
    grouped: dict[int, list[_MeasureNote]] = {}
    for segment in segments:
        grouped.setdefault(segment.measure_number, []).append(segment)

    for measure_number in range(1, max(grouped, default=1) + 1):
        measure = ET.SubElement(part, "measure", number=str(measure_number))
        if measure_number == 1:
            attributes = ET.SubElement(measure, "attributes")
            ET.SubElement(attributes, "divisions").text = str(divisions)
            time = ET.SubElement(attributes, "time")
            ET.SubElement(time, "beats").text = str(project.tab.time_signature[0])
            ET.SubElement(time, "beat-type").text = str(project.tab.time_signature[1])
            clef = ET.SubElement(attributes, "clef")
            ET.SubElement(clef, "sign").text = "TAB"
            ET.SubElement(clef, "line").text = "5"
            staff_details = ET.SubElement(attributes, "staff-details")
            ET.SubElement(staff_details, "staff-lines").text = str(len(project.tab.tuning))
            for line, open_pitch in enumerate(project.tab.tuning, start=1):
                tuning = ET.SubElement(staff_details, "staff-tuning", line=str(line))
                step, alter, octave = _pitch_parts(open_pitch)
                ET.SubElement(tuning, "tuning-step").text = step
                if alter:
                    ET.SubElement(tuning, "tuning-alter").text = str(alter)
                ET.SubElement(tuning, "tuning-octave").text = str(octave)
            direction = ET.SubElement(measure, "direction", placement="above")
            direction_type = ET.SubElement(direction, "direction-type")
            metronome = ET.SubElement(direction_type, "metronome")
            ET.SubElement(metronome, "beat-unit").text = "quarter"
            tempo = f"{project.tab.tempo_bpm:g}"
            ET.SubElement(metronome, "per-minute").text = tempo
            ET.SubElement(direction, "sound", tempo=tempo)
        cursor = (measure_number - 1) * ticks_per_measure
        for segment in grouped.get(measure_number, []):
            if segment.start_tick > cursor:
                forward = ET.SubElement(measure, "forward")
                ET.SubElement(forward, "duration").text = str(segment.start_tick - cursor)
            _append_musicxml_note(measure, segment)
            cursor = segment.start_tick + segment.duration_ticks
    ET.indent(score, space="  ")
    return ET.tostring(score, encoding="utf-8", xml_declaration=True)


def midi(project: Project) -> bytes:
    midi_file = mido.MidiFile(type=1, ticks_per_beat=project.tab.ticks_per_quarter)
    track = mido.MidiTrack()
    midi_file.tracks.append(track)
    tempo = mido.bpm2tempo(project.tab.tempo_bpm)
    midi_title = project.title.encode("latin-1", "replace").decode("latin-1")
    track.append(mido.MetaMessage("track_name", name=midi_title, time=0))
    track.append(mido.MetaMessage("set_tempo", tempo=round(tempo), time=0))
    events: list[tuple[int, int, mido.Message]] = []
    for note in project.tab.notes:
        events.append(
            (
                note.score_tick,
                1,
                mido.Message("note_on", note=note.midi_pitch, velocity=82, time=0),
            )
        )
        events.append(
            (
                note.score_tick + note.duration_ticks,
                0,
                mido.Message("note_off", note=note.midi_pitch, velocity=0, time=0),
            )
        )
    previous_tick = 0
    for tick, _, message in sorted(events, key=lambda event: (event[0], event[1])):
        message.time = max(0, tick - previous_tick)
        track.append(message)
        previous_tick = tick
    output = io.BytesIO()
    midi_file.save(file=output)
    return output.getvalue()


def project_json(project: Project) -> bytes:
    return (json.dumps(project.model_dump(mode="json"), indent=2) + "\n").encode()


def _bundle_asset_paths(project: Project, directory: Path) -> list[tuple[Path, str]]:
    paths: list[tuple[Path, str]] = []
    for asset in project.assets:
        path = directory / asset.filename
        if not path.is_file():
            raise FileNotFoundError(
                f"Cannot create bundle: declared {asset.role} asset is missing "
                f"({asset.filename})"
            )
        paths.append((path, f"{project.id}/audio/{asset.filename}"))
    return paths


def bundle(project: Project, directory: Path) -> bytes:
    asset_paths = _bundle_asset_paths(project, directory)
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        _write_bundle(archive, project, asset_paths)
    return output.getvalue()


def _write_bundle(
    archive: zipfile.ZipFile,
    project: Project,
    asset_paths: list[tuple[Path, str]],
) -> None:
    archive.writestr(f"{project.id}/project.json", project_json(project))
    archive.writestr(f"{project.id}/tab.musicxml", musicxml(project))
    archive.writestr(f"{project.id}/reference.mid", midi(project))
    archive.writestr(f"{project.id}/tab.txt", ascii_tab(project))
    for path, archive_name in asset_paths:
        archive.write(path, archive_name)


def write_bundle(project: Project, directory: Path, destination: Path) -> Path:
    asset_paths = _bundle_asset_paths(project, directory)
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        _write_bundle(archive, project, asset_paths)
    return destination


def export_filename(project: Project, format_name: str) -> str:
    ascii_title = (
        unicodedata.normalize("NFKD", project.title)
        .encode("ascii", "ignore")
        .decode("ascii")
    )
    safe_title = "".join(
        character.lower() if character.isalnum() else "-"
        for character in ascii_title
    ).strip("-")
    safe_title = "-".join(filter(None, safe_title.split("-"))) or project.id
    suffixes = {
        "json": ".solotrace.json",
        "musicxml": ".musicxml",
        "midi": ".mid",
        "ascii": ".txt",
        "bundle": ".solotrace.zip",
    }
    try:
        return f"{safe_title}{suffixes[format_name]}"
    except KeyError as error:
        raise ValueError(f"Unsupported export format: {format_name}") from error


def export_payload(
    project: Project,
    directory: Path,
    format_name: str,
) -> tuple[bytes, str, str]:
    filename = export_filename(project, format_name)
    if format_name == "json":
        return project_json(project), "application/json", filename
    if format_name == "musicxml":
        return (
            musicxml(project),
            "application/vnd.recordare.musicxml+xml",
            filename,
        )
    if format_name == "midi":
        return midi(project), "audio/midi", filename
    if format_name == "ascii":
        return ascii_tab(project).encode(), "text/plain; charset=utf-8", filename
    if format_name == "bundle":
        return bundle(project, directory), "application/zip", filename
    raise ValueError(f"Unsupported export format: {format_name}")
