from __future__ import annotations

import io
import json
import unicodedata
import zipfile
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from xml.etree import ElementTree as ET

import mido

from .beat_map import TempoEvent, pickup_midi_shift, tempo_events_for_tab
from .models import ChordEvent, NoteEvent, Project
from .version import APP_VERSION

PITCH_NAMES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")
PROJECT_FORMAT = "solotrace-project"
PROJECT_SCHEMA_VERSION = 3


def pitch_name(midi_pitch: int) -> str:
    return f"{PITCH_NAMES[midi_pitch % 12]}{midi_pitch // 12 - 1}"


def ascii_tab(project: Project, width: int = 72) -> str:
    notes = project.tab.notes
    if not notes:
        return "No notes yet.\n"
    start = project.passage.start_s
    end = project.passage.end_s
    duration = max(0.01, end - start)
    string_count = len(project.tab.tuning)
    lines = {string: ["-"] * width for string in range(1, string_count + 1)}
    for note in sorted(notes, key=lambda item: (item.audio_onset_s, item.string)):
        column = min(
            width - 2,
            max(0, round((note.audio_onset_s - start) / duration * (width - 3))),
        )
        text = str(note.fret)
        if "bend" in note.techniques:
            text += "b"
        while True:
            required = column + len(text) + 1
            if required > len(lines[note.string]):
                extension = required - len(lines[note.string])
                for line in lines.values():
                    line.extend("-" * extension)
            if all(
                lines[note.string][column + offset] == "-"
                for offset in range(len(text))
            ):
                break
            column += 1
        for offset, character in enumerate(text):
            lines[note.string][column + offset] = character
    labels = {
        string: pitch_name(open_pitch)
        for string, open_pitch in enumerate(reversed(project.tab.sounding_tuning), start=1)
    }
    result = [f"{project.title} — {project.passage.name}", ""]
    result.extend(
        f"{labels[string]:>3}|{''.join(lines[string])}|"
        for string in range(1, string_count + 1)
    )
    result.append("")
    result.append("Generated by SoloTrace; verify uncertain notes against the recording.")
    return "\n".join(result) + "\n"


def _pitch_parts(midi_pitch: int) -> tuple[str, int, int]:
    names = [
        ("C", 0),
        ("C", 1),
        ("D", 0),
        ("D", 1),
        ("E", 0),
        ("F", 0),
        ("F", 1),
        ("G", 0),
        ("G", 1),
        ("A", 0),
        ("A", 1),
        ("B", 0),
    ]
    step, alter = names[midi_pitch % 12]
    octave = midi_pitch // 12 - 1
    return step, alter, octave


@dataclass(frozen=True)
class _MeasureNote:
    event: NoteEvent
    measure_number: int
    start_tick: int
    duration_ticks: int
    tie_stop: bool
    tie_start: bool


@dataclass(frozen=True)
class _MeasureLocation:
    measure_number: int
    start_tick: int
    end_tick: int
    implicit: bool


def _measure_ticks(project: Project) -> int:
    beats, beat_type = project.tab.time_signature
    if beats <= 0 or beat_type <= 0:
        raise ValueError("Time signature values must be positive")
    measure_ticks = Fraction(
        beats * project.tab.ticks_per_quarter * 4,
        beat_type,
    )
    if measure_ticks.denominator != 1:
        raise ValueError(
            "Time signature cannot be represented exactly with the current "
            "ticks-per-quarter value"
        )
    return measure_ticks.numerator


def _bar_offset_ticks(project: Project) -> int:
    return getattr(project.tab, "bar_offset_ticks", 0)


def _measure_location_for_tick(
    tick: int,
    ticks_per_measure: int,
    bar_offset_ticks: int,
) -> _MeasureLocation:
    if bar_offset_ticks > 0 and tick < bar_offset_ticks:
        return _MeasureLocation(0, 0, bar_offset_ticks, True)
    adjusted = max(0, tick - bar_offset_ticks)
    index = adjusted // ticks_per_measure
    return _MeasureLocation(
        index + 1,
        bar_offset_ticks + index * ticks_per_measure,
        bar_offset_ticks + (index + 1) * ticks_per_measure,
        False,
    )


def _split_musicxml_notes(
    project: Project,
    ticks_per_measure: int,
    bar_offset_ticks: int,
) -> list[_MeasureNote]:
    segments: list[_MeasureNote] = []
    previous_end = 0
    for event in sorted(project.tab.notes, key=lambda note: (note.score_tick, note.id)):
        if event.score_tick < previous_end:
            raise ValueError("MusicXML export requires a monophonic tab without overlapping notes")
        event_end = event.score_tick + event.duration_ticks
        segment_start = event.score_tick
        while segment_start < event_end:
            location = _measure_location_for_tick(
                segment_start,
                ticks_per_measure,
                bar_offset_ticks,
            )
            segment_end = min(event_end, location.end_tick)
            segments.append(
                _MeasureNote(
                    event=event,
                    measure_number=location.measure_number,
                    start_tick=segment_start,
                    duration_ticks=segment_end - segment_start,
                    tie_stop=segment_start > event.score_tick,
                    tie_start=segment_end < event_end,
                )
            )
            segment_start = segment_end
        previous_end = event_end
    return segments


def _append_musicxml_note(measure: ET.Element, segment: _MeasureNote) -> None:
    event = segment.event
    note = ET.SubElement(measure, "note")
    pitch = ET.SubElement(note, "pitch")
    step, alter, octave = _pitch_parts(event.midi_pitch)
    ET.SubElement(pitch, "step").text = step
    if alter:
        ET.SubElement(pitch, "alter").text = str(alter)
    ET.SubElement(pitch, "octave").text = str(octave)
    ET.SubElement(note, "duration").text = str(segment.duration_ticks)
    if segment.tie_stop:
        ET.SubElement(note, "tie", type="stop")
    if segment.tie_start:
        ET.SubElement(note, "tie", type="start")
    ET.SubElement(note, "voice").text = "1"
    notations = ET.SubElement(note, "notations")
    if segment.tie_stop:
        ET.SubElement(notations, "tied", type="stop")
    if segment.tie_start:
        ET.SubElement(notations, "tied", type="start")
    technical = ET.SubElement(notations, "technical")
    ET.SubElement(technical, "string").text = str(event.string)
    ET.SubElement(technical, "fret").text = str(event.fret)
    if "bend" in event.techniques:
        bend = ET.SubElement(technical, "bend")
        bend_cents = (
            max(event.pitch_curve_cents) - min(event.pitch_curve_cents)
            if event.pitch_curve_cents
            else 100
        )
        if bend_cents <= 0:
            bend_cents = 100
        ET.SubElement(bend, "bend-alter").text = str(
            round(bend_cents / 100, 2)
        )


def _append_musicxml_harmony(
    measure: ET.Element,
    chord: ChordEvent,
    measure_start: int,
) -> None:
    harmony = ET.SubElement(measure, "harmony")
    if chord.kind == "chord":
        assert chord.root is not None and chord.quality is not None
        root = ET.SubElement(harmony, "root")
        ET.SubElement(root, "root-step").text = chord.root.step
        if chord.root.alter:
            ET.SubElement(root, "root-alter").text = str(chord.root.alter)
        kind_names = {
            "min": "minor",
            "maj": "major",
            "dim": "diminished",
            "aug": "augmented",
            "min6": "minor-sixth",
            "maj6": "major-sixth",
            "min7": "minor-seventh",
            "minmaj7": "major-minor",
            "maj7": "major-seventh",
            "7": "dominant",
            "dim7": "diminished-seventh",
            "hdim7": "half-diminished",
            "sus2": "suspended-second",
            "sus4": "suspended-fourth",
        }
        ET.SubElement(harmony, "kind").text = kind_names[chord.quality]
        if chord.bass is not None:
            bass = ET.SubElement(harmony, "bass")
            ET.SubElement(bass, "bass-step").text = chord.bass.step
            if chord.bass.alter:
                ET.SubElement(bass, "bass-alter").text = str(chord.bass.alter)
    else:
        kind = ET.SubElement(harmony, "kind", text="N.C." if chord.kind == "no-chord" else "X")
        kind.text = "none" if chord.kind == "no-chord" else "other"
    offset = max(0, chord.score_tick - measure_start)
    if offset:
        ET.SubElement(harmony, "offset").text = str(offset)


def _append_musicxml_tempo(
    measure: ET.Element,
    bpm: float,
    offset: int,
    *,
    hidden: bool,
) -> None:
    attributes = {"placement": "above"}
    if hidden:
        attributes["print-object"] = "no"
    direction = ET.SubElement(measure, "direction", attributes)
    direction_type = ET.SubElement(direction, "direction-type")
    metronome = ET.SubElement(direction_type, "metronome")
    ET.SubElement(metronome, "beat-unit").text = "quarter"
    tempo = f"{bpm:g}"
    ET.SubElement(metronome, "per-minute").text = tempo
    if offset:
        ET.SubElement(direction, "offset").text = str(offset)
    ET.SubElement(direction, "sound", tempo=tempo)


def musicxml(project: Project) -> bytes:
    score = ET.Element("score-partwise", version="4.0")
    work = ET.SubElement(score, "work")
    ET.SubElement(work, "work-title").text = project.title
    part_list = ET.SubElement(score, "part-list")
    score_part = ET.SubElement(part_list, "score-part", id="P1")
    ET.SubElement(score_part, "part-name").text = "Lead guitar"
    part = ET.SubElement(score, "part", id="P1")
    divisions = project.tab.ticks_per_quarter
    ticks_per_measure = _measure_ticks(project)
    bar_offset_ticks = _bar_offset_ticks(project)
    segments = _split_musicxml_notes(project, ticks_per_measure, bar_offset_ticks)
    grouped: dict[int, list[_MeasureNote]] = {}
    for segment in segments:
        grouped.setdefault(segment.measure_number, []).append(segment)
    harmonies: dict[int, list[ChordEvent]] = {}
    for chord in project.tab.chords.events:
        measure_number = _measure_location_for_tick(
            chord.score_tick,
            ticks_per_measure,
            bar_offset_ticks,
        ).measure_number
        harmonies.setdefault(measure_number, []).append(chord)

    tempos: dict[int, list[TempoEvent]] = {}
    final_event_tick = max(
        [
            *(note.score_tick + note.duration_ticks for note in project.tab.notes),
            *(chord.score_tick + chord.duration_ticks for chord in project.tab.chords.events),
            0,
        ]
    )
    for tempo_event in tempo_events_for_tab(project.tab):
        if tempo_event.score_tick > final_event_tick:
            continue
        measure_number = _measure_location_for_tick(
            tempo_event.score_tick,
            ticks_per_measure,
            bar_offset_ticks,
        ).measure_number
        tempos.setdefault(measure_number, []).append(tempo_event)

    final_measure = max(
        max(grouped, default=1),
        max(harmonies, default=1),
        max(tempos, default=1),
    )
    first_measure = 0 if bar_offset_ticks else 1
    for measure_number in range(first_measure, final_measure + 1):
        measure_tick = (
            0
            if measure_number == 0
            else bar_offset_ticks + (measure_number - 1) * ticks_per_measure
        )
        location = _measure_location_for_tick(
            measure_tick,
            ticks_per_measure,
            bar_offset_ticks,
        )
        measure_attributes = {"number": str(measure_number)}
        if location.implicit:
            measure_attributes["implicit"] = "yes"
        measure = ET.SubElement(part, "measure", measure_attributes)
        if measure_number == first_measure:
            attributes = ET.SubElement(measure, "attributes")
            ET.SubElement(attributes, "divisions").text = str(divisions)
            time = ET.SubElement(attributes, "time")
            ET.SubElement(time, "beats").text = str(project.tab.time_signature[0])
            ET.SubElement(time, "beat-type").text = str(project.tab.time_signature[1])
            clef = ET.SubElement(attributes, "clef")
            ET.SubElement(clef, "sign").text = "TAB"
            ET.SubElement(clef, "line").text = "5"
            staff_details = ET.SubElement(attributes, "staff-details")
            ET.SubElement(staff_details, "staff-lines").text = str(len(project.tab.tuning))
            if project.tab.capo_fret:
                ET.SubElement(staff_details, "capo").text = str(project.tab.capo_fret)
            for line, open_pitch in enumerate(project.tab.tuning, start=1):
                tuning = ET.SubElement(staff_details, "staff-tuning", line=str(line))
                step, alter, octave = _pitch_parts(open_pitch)
                ET.SubElement(tuning, "tuning-step").text = step
                if alter:
                    ET.SubElement(tuning, "tuning-alter").text = str(alter)
                ET.SubElement(tuning, "tuning-octave").text = str(octave)
        measure_start = location.start_tick
        for index, tempo_event in enumerate(tempos.get(measure_number, [])):
            _append_musicxml_tempo(
                measure,
                tempo_event.bpm,
                max(0, tempo_event.score_tick - measure_start),
                hidden=measure_number != first_measure or index > 0,
            )
        for chord in sorted(
            harmonies.get(measure_number, []),
            key=lambda event: (event.score_tick, event.id),
        ):
            _append_musicxml_harmony(measure, chord, measure_start)
        cursor = measure_start
        for segment in grouped.get(measure_number, []):
            if segment.start_tick > cursor:
                forward = ET.SubElement(measure, "forward")
                ET.SubElement(forward, "duration").text = str(segment.start_tick - cursor)
            _append_musicxml_note(measure, segment)
            cursor = segment.start_tick + segment.duration_ticks
    ET.indent(score, space="  ")
    return ET.tostring(score, encoding="utf-8", xml_declaration=True)


def midi(project: Project) -> bytes:
    midi_file = mido.MidiFile(type=1, ticks_per_beat=project.tab.ticks_per_quarter)
    track = mido.MidiTrack()
    midi_file.tracks.append(track)
    midi_title = project.title.encode("latin-1", "replace").decode("latin-1")
    track.append(mido.MetaMessage("track_name", name=midi_title, time=0))
    beats, beat_type = project.tab.time_signature
    track.append(
        mido.MetaMessage(
            "time_signature",
            numerator=beats,
            denominator=beat_type,
            clocks_per_click=36 if beat_type == 8 and beats > 3 and beats % 3 == 0 else 24,
            time=0,
        )
    )
    events: list[tuple[int, int, mido.Message | mido.MetaMessage]] = []
    pickup_shift = pickup_midi_shift(project.tab)
    for index, tempo_event in enumerate(tempo_events_for_tab(project.tab)):
        events.append(
            (
                0 if index == 0 else tempo_event.score_tick + pickup_shift,
                -2,
                mido.MetaMessage(
                    "set_tempo",
                    tempo=round(mido.bpm2tempo(tempo_event.bpm)),
                    time=0,
                ),
            )
        )
    for note in project.tab.notes:
        events.append(
            (
                note.score_tick + pickup_shift,
                1,
                mido.Message("note_on", note=note.midi_pitch, velocity=82, time=0),
            )
        )
        events.append(
            (
                note.score_tick + note.duration_ticks + pickup_shift,
                0,
                mido.Message("note_off", note=note.midi_pitch, velocity=0, time=0),
            )
        )
    previous_tick = 0
    for tick, _, message in sorted(events, key=lambda event: (event[0], event[1])):
        message.time = max(0, tick - previous_tick)
        track.append(message)
        previous_tick = tick
    output = io.BytesIO()
    midi_file.save(file=output)
    return output.getvalue()


def project_json(project: Project, *, all_versions: bool = False) -> bytes:
    payload = project.model_dump(mode="json")
    if not all_versions:
        payload["versions"] = [
            version
            for version in payload["versions"]
            if version["id"] == project.active_version_id
        ]
    envelope = {
        "format": PROJECT_FORMAT,
        "schemaVersion": PROJECT_SCHEMA_VERSION,
        "appVersion": APP_VERSION,
        "project": payload,
    }
    return (json.dumps(envelope, indent=2) + "\n").encode()


def _bundle_asset_paths(project: Project, directory: Path) -> list[tuple[Path, str]]:
    paths: list[tuple[Path, str]] = []
    for asset in project.assets:
        path = directory / asset.filename
        if not path.is_file():
            raise FileNotFoundError(
                f"Cannot create bundle: declared {asset.role} asset is missing "
                f"({asset.filename})"
            )
        paths.append((path, f"{project.id}/audio/{asset.filename}"))
    return paths


def bundle(project: Project, directory: Path) -> bytes:
    asset_paths = _bundle_asset_paths(project, directory)
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        _write_bundle(archive, project, asset_paths)
    return output.getvalue()


def _write_bundle(
    archive: zipfile.ZipFile,
    project: Project,
    asset_paths: list[tuple[Path, str]],
) -> None:
    archive.writestr(
        f"{project.id}/project.json",
        project_json(project, all_versions=True),
    )
    for version in project.versions:
        version_project = project.model_copy(update={"active_version_id": version.id})
        version_root = f"{project.id}/versions/{version.id}"
        derived_exports = (
            ("tab.musicxml", musicxml),
            ("reference.mid", midi),
            ("tab.txt", ascii_tab),
        )
        for filename, render in derived_exports:
            try:
                archive.writestr(f"{version_root}/{filename}", render(version_project))
            except ValueError:
                # The manifest and audio are the lossless, re-importable bundle.
                # A notation limitation must not prevent users from backing it up.
                continue
    for path, archive_name in asset_paths:
        archive.write(path, archive_name)


def write_bundle(project: Project, directory: Path, destination: Path) -> Path:
    asset_paths = _bundle_asset_paths(project, directory)
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        _write_bundle(archive, project, asset_paths)
    return destination


def export_filename(project: Project, format_name: str) -> str:
    ascii_title = (
        unicodedata.normalize("NFKD", project.title)
        .encode("ascii", "ignore")
        .decode("ascii")
    )
    safe_title = "".join(
        character.lower() if character.isalnum() else "-"
        for character in ascii_title
    ).strip("-")
    safe_title = "-".join(filter(None, safe_title.split("-"))) or project.id
    suffixes = {
        "json": ".solotrace.json",
        "musicxml": ".musicxml",
        "midi": ".mid",
        "ascii": ".txt",
        "bundle": ".solotrace.zip",
    }
    try:
        return f"{safe_title}{suffixes[format_name]}"
    except KeyError as error:
        raise ValueError(f"Unsupported export format: {format_name}") from error


def export_payload(
    project: Project,
    directory: Path,
    format_name: str,
) -> tuple[bytes, str, str]:
    filename = export_filename(project, format_name)
    if format_name == "json":
        return project_json(project), "application/json", filename
    if format_name == "musicxml":
        return (
            musicxml(project),
            "application/vnd.recordare.musicxml+xml",
            filename,
        )
    if format_name == "midi":
        return midi(project), "audio/midi", filename
    if format_name == "ascii":
        return ascii_tab(project).encode(), "text/plain; charset=utf-8", filename
    if format_name == "bundle":
        return bundle(project, directory), "application/zip", filename
    raise ValueError(f"Unsupported export format: {format_name}")
